name: Playwright Tests
on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *" # Check every 15 minutes
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-22.04
    steps:
    - name: Check if time to run
      run: |
        CURRENT_TIME=$(date +%s)
        NEXT_RUN_TIME=${{ vars.NEXT_RUN_TIME }}
        if [ -z "$NEXT_RUN_TIME" ] || [ $CURRENT_TIME -ge $NEXT_RUN_TIME ]; then
          echo "TIME_TO_RUN=true" >> $GITHUB_ENV
        else
          echo "TIME_TO_RUN=false" >> $GITHUB_ENV
          echo "Not time yet, skipping"
          exit 0
        fi
    - uses: actions/checkout@v4
      if: ${{ env.TIME_TO_RUN == 'true' }}
    - uses: actions/cache@v4
      if: ${{ env.TIME_TO_RUN == 'true' }}
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
    - uses: actions/setup-node@v4
      if: ${{ env.TIME_TO_RUN == 'true' }}
      with:
        node-version: lts/*
    - name: Install dependencies
      if: ${{ env.TIME_TO_RUN == 'true' }}
      run: npm ci
    - name: Install Playwright Browsers
      if: ${{ env.TIME_TO_RUN == 'true' }}
      run: npx playwright install --with-deps chromium
    - name: Create .env file
      if: ${{ env.TIME_TO_RUN == 'true' }}
      run: |
        touch .env
        echo "EMAIL=${{ secrets.EMAIL }}" >> .env
        echo "PASSWORD=${{ secrets.PASSWORD }}" >> .env
        echo "MAX_FUEL_PRICE=${{ vars.MAX_FUEL_PRICE }}" >> .env
        echo "MAX_CO2_PRICE=${{ vars.MAX_CO2_PRICE }}" >> .env
        echo "INCREASE_AIRLINE_REPUTATION=${{ vars.INCREASE_AIRLINE_REPUTATION }}" >> .env
        echo "CAMPAIGN_TYPE=${{ vars.CAMPAIGN_TYPE }}" >> .env
        echo "CAMPAIGN_DURATION=${{ vars.CAMPAIGN_DURATION }}" >> .env
    - name: Run Playwright tests
      if: ${{ env.TIME_TO_RUN == 'true' }}
      run: npx playwright test
    - name: Update next run time
      if: ${{ env.TIME_TO_RUN == 'true' }}
      run: |
        CURRENT_TIME=$(date +%s)
        RANDOM_HOURS=$((1 + RANDOM % 6))
        NEXT_TIME=$((CURRENT_TIME + RANDOM_HOURS * 3600))
        curl -L \
          -X PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/actions/variables/NEXT_RUN_TIME \
          -d "{\"name\":\"NEXT_RUN_TIME\",\"value\":\"$NEXT_TIME\"}"
    # - uses: actions/upload-artifact@v4
    #   if: always()
    #   with:
    #     name: playwright-report
    #     path: playwright-report/
    #     retention-days: 1
